### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by wh1sk31** [Kieran-Lock/AutoKahoot#2]
~/KahootH/AutoKahoot$ python3 main.py
Quiz ID:    45db2b22-f7d5-423c-8f99-2b1f1c8862f3
Lobby Pin:  9768414
Bot Username:   Test
Exception in callback TransportBase._connect_done(<Task cancell.../utils.py:22>>)
handle: <Handle TransportBase._connect_done(<Task cancell.../utils.py:22>>)>
Traceback (most recent call last):
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/utils.py", line 27, in wrapper
    return await coro_func(*args, **kwargs)
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/base.py", line 486, in _connect
    result = await self._send_payload_with_auth(payload)
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/base.py", line 280, in _send_payload_with_auth
    response = await self._send_payload(payload)
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/base.py", line 307, in _send_payload
    return await self._send_final_payload(payload, headers=headers)
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/websocket.py", line 169, in _send_final_payload
    return await self._send_socket_payload(socket, payload)
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/websocket.py", line 209, in _send_socket_payload
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/base.py", line 503, in _connect_done
    result: Union[JsonObject, Exception] = future.result()
asyncio.exceptions.CancelledError
Exception in callback WebSocketTransport._receive_done(<Task cancell...ocket.py:222>>)
handle: <Handle WebSocketTransport._receive_done(<Task cancell...ocket.py:222>>)>
Traceback (most recent call last):
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/websocket.py", line 230, in _receive
    response = await socket.receive()
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiohttp/client_ws.py", line 244, in receive
    msg = await self._reader.read()
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiohttp/streams.py", line 681, in read
    return await super().read()
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/runner/KahootH/.pythonlibs/lib/python3.10/site-packages/aiocometd_noloop/transports/websocket.py", line 259, in _receive_done
    result = future.result()
asyncio.exceptions.CancelledError
Traceback (most recent call last):
  File "/home/runner/KahootH/AutoKahoot/main.py", line 21, in <module>
    run(main())
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/KahootH/AutoKahoot/main.py", line 17, in main
    await bot.play(lobby, client)
  File "/home/runner/KahootH/AutoKahoot/autokahoot/bot.py", line 29, in play
    await lobby.quiz.rounds[question_index].send_answer(client, lobby)
TypeError: list indices must be integers or slices, not NoneType

**Comment by Kieran-Lock** [comment]
hey @wh1sk31, it looks like Kahoot have changed the structure of some of their internal events.
I've tried to put in a quick fix, so can you try pulling the latest changes to this repo and trying again? Thanks
